micronaut:
  application:
    name: realworld-backend-micronaut
  server:
    host: ${HOST:0.0.0.0}
    port: ${PORT:8080}
    cors:
      enabled: true
    thread-selection: AUTO
  security:
    enabled: true
    intercept-url-map:
      - pattern: /**
        httpMethod: OPTIONS
        access:
          - isAnonymous()
      - pattern: /swagger/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /swagger-ui/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: ${api.version}/articles/feed
        httpMethod: GET
        access:
          - isAuthenticated()
      - pattern: ${api.version}/users/**
        httpMethod: POST
        access:
          - isAnonymous()
      - pattern: ${api.version}/articles/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: ${api.version}/profiles/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: ${api.version}/tags/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: ${api.version}/**
        access:
          - isAuthenticated()
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
---
jpa:
 default:
    properties:
        hibernate:
            hbm2ddl:
              auto: none
            bytecode:
              provider: none
---
jackson:
  serializationInclusion: ALWAYS
  serialization:
    fail_on_empty_beans: false
    write_dates_as_timestamps: false
  deserialization:
    unwrap_root_value: true
---
endpoints:
  info:
    enabled: true
    sensitive: false
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS
    jdbc:
      enabled: true
    discovery-client:
      enabled: false
    disk-space:
      enabled: false
  prometheus:
    enabled: true
    sensitive: false

security:
  jwt:
    secret: MWY1MmQ2NTItODIxNC00ZGM0LWFiODQtOGFiNGZmMjlhZjdj

api:
  version: /api

liquibase:
  enabled: true
  datasources:
    default:
      change-log: "classpath:db/database-changelog.xml"
