micronaut:
  application:
    name: realworld-micronaut-backend
  server:
    host: 0.0.0.0
    port: ${PORT:8080}
    cors:
      enabled: true
---
datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
---
jpa:
 default:
    properties:
        hibernate:
            hbm2ddl:
              auto: update
            bytecode:
              provider: none
---
jackson:
  serialization:
    failOnEmptyBeans: false
    writeDatesAsTimestamps: true